name: Check CODEOWNERS owner change

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  check-owners-change:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if CODEOWNERS owner changed
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          if echo "$CHANGED_FILES" | grep -q CODEOWNERS; then
            NEW_OWNER=$(grep -E "^\*?\s*@\S+\b" CODEOWNERS | sed "s/.*@\([[:alnum:]-]\+\).*/\1/" | head -n 1)
            echo "The owner in CODEOWNERS file has been changed to $NEW_OWNER" >> output.txt
          fi

      - name: Commit changes to output.txt
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git checkout main
          git add output.txt
          git commit -m "Update output.txt file with owner change message"
          git push
