name: Add Owner to File

on:
  push:
    branches:
      - main

jobs:
  add-owner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read owner from file
        run: |
          OWNER=$(cat owner.txt)
          echo "OWNER=$OWNER" >> $GITHUB_ENV

      - name: Add owner to file
        uses: peter-evans/create-file@v2
        with:
          path: 'owner.txt'
          content: ${{ env.OWNER }}
