name: Add owner to file

on:
  workflow_run:
    workflows:
      - "Extract CODEOWNERS file owner"
    branches-ignore:
      - main
    types:
      - completed

jobs:
  add-owner-to-file:
    runs-on: ubuntu-latest
    needs: extract-owner
    steps:
      - uses: actions/checkout@v2
      - name: Create text file in main branch with owner username
        uses: actions/github-script@v5
        with:
          script: |
            const ownerUsername = "${{ steps.extract-owner.outputs.username }}";
            const content = `New owner: @${ownerUsername}`;
            const filePath = 'new_owner.txt';

            const { data: branch } = await github.rest.repos.getBranch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'main'
            });

            await github.rest.repos.createOrUpdateFileContents({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: filePath,
              message: `Add new owner file for ${ownerUsername}`,
              content: Buffer.from(content).toString('base64'),
              branch: 'main',
              sha: branch.commit.sha,
              token: ${{ secrets.GITHUB_TOKEN }}
            });
