name: CODEOWNERS Changes

on:
  push:
    branches-ignore:
      - main
    paths:
      - '**/CODEOWNERS'

jobs:
  codeowners-changes:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Print hello message
      run: |
        old_owner=$(awk '$1 ~ /^.*$/ {print $1}' ${{ github.event.inputs.before }}CODEOWNERS)
        new_owner=$(awk '$1 ~ /^.*$/ {print $1}' ${{ github.event.inputs.after }}CODEOWNERS)
       
          echo "Hello $new_owner! You are now an owner of the file in the CODEOWNERS file."
        fi
