name: CODEOWNERS Update Notification

on:
  push:
    branches-ignore:
      - main
    paths:
      - '**/CODEOWNERS'

jobs:
  codeowners-update-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello! A CODEOWNERS file has been updated in a non-main branch."
