name: Extract Owner

on:
  push:
    branches:
      - "!main"

jobs:
  extract-owner:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPOSITORY: ${{ github.repository }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract owner
        run: |
          OWNER=$(grep -E "^\*?\s*@\S+\b" CODEOWNERS | sed "s/.*@\([[:alnum:]-]\+\).*/\1/" | head -n 1)
          echo "OWNER=$OWNER" >> $GITHUB_ENV

      - name: Add owner to file
        uses: peter-evans/create-file@v2
        with:
          path: 'owner.txt'
          content: ${{ env.OWNER }}
