name: Update tsc.json

on:
  push:
    paths:
      - 'CODEOWNERS'

jobs:
  update_tsc_json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current branch
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install jq

    - name: Extract owner and repo from CODEOWNERS
      id: extract_info
      run: |
        username=$(grep -oP 'test\.txt \@(\w+)' CODEOWNERS | grep -oP '\@\w+' | sed 's/@//')
        repo_name=$(basename $(git remote get-url origin) .git)
        echo "::set-output name=username::$username"
        echo "::set-output name=repo_name::$repo_name"

    - name: Check if owner exists in tsc.json
      id: check_owner
      run: |
        username="${{ steps.extract_info.outputs.username }}"
        found=$(jq ".[] | select(.github == \"$username\")" tsc.json)
        echo "::set-output name=found::$found"

    - name: Add new member to tsc.json
      if: steps.check_owner.outputs.found == ''
      run: |
        username="${{ steps.extract_info.outputs.username }}"
        repo_name="${{ steps.extract_info.outputs.repo_name }}"
        jq --arg github "$username" --arg repo "$repo_name" '. += [{ "name": "", "github": $github, "linkedin": "", "slack": "", "twitter": "", "availableForHire": false, "repos": [$repo] }]' tsc.json > tsc_temp.json
        mv tsc_temp.json tsc.json

    - name: Commit and push changes
      if: steps.check_owner.outputs.found == ''
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "your_email@example.com"
        git add tsc.json
        git commit -m "Update tsc.json with a new member"
        git remote set-url origin "https://x-access-token:${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}@github.com/sparsh-989/project.git"
        git push origin HEAD
