name: Update tsc.json

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'CODEOWNERS'

jobs:
  update_tsc_json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current branch
      uses: actions/checkout@v2

    - name: Checkout main branch
      run: |
        git fetch origin main:main
        git checkout main

    - name: Add new member to tsc.json
      run: |
        echo '{
          "name": "New Member",
          "github": "newmember",
          "linkedin": "newmember",
          "slack": "U01XXXXX",
          "twitter": "newmember",
          "availableForHire": true,
          "repos": [
            "new-repo"
          ]
        }' >> tsc.json

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "your_email@example.com"
        git add tsc.json
        git commit -m "Update tsc.json with a new member"
        git remote set-url origin "https://x-access-token:${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}@github.com/sparsh-989/project.git"
        git push origin main
