name: Update example.txt

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'CODEOWNERS'

jobs:
  update_example_txt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current branch
      uses: actions/checkout@v2

    - name: Checkout main branch
      run: |
        git fetch origin main:main
        git checkout main

    - name: Write hello message to example.txt
      run: |
        echo "Hello" >> example.txt

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "your_email@example.com"
        git add example.txt
        git commit -m "Update example.txt with a hello message"
        git remote set-url origin "https://x-access-token:${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}@github.com/sparsh-989/project.git"
        git push origin main
