name: Update tsc.json

on:
  push:
    paths:
      - 'CODEOWNERS'

jobs:
  update_tsc_json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current branch
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Checkout main branch
      run: |
        git fetch origin main:main
        git checkout main

    - name: Check if user exists and update tsc.json
      env:
        CODEOWNERS_FILE: ${{ github.workspace }}/CODEOWNERS
        TSC_JSON_FILE: ${{ github.workspace }}/tsc.json
      run: |
        git diff HEAD^ HEAD -- $CODEOWNERS_FILE | grep "^+" | grep -v "^+++" | while read -r line; do
          username=$(echo "$line" | awk '{print $NF}' | sed 's/@//g')
          repo=$(echo "$line" | awk -F'/' '{print $1}')
          if ! jq '.[] | select(.github == "'$username'")' $TSC_JSON_FILE > /dev/null; then
            jq '. |= .+ [{
              "name": "New Member",
              "github": "'$username'",
              "linkedin": "",
              "slack": "",
              "twitter": "",
              "availableForHire": false,
              "repos": ["'$repo'"]
            }]' $TSC_JSON_FILE > tsc.json.tmp && mv tsc.json.tmp $TSC_JSON_FILE
            git config user.name "GitHub Actions Bot"
            git config user.email "your_email@example.com"
            git add $TSC_JSON_FILE
            git commit -m "Update tsc.json with a new member"
            git remote set-url origin "https://x-access-token:${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}@github.com/your-username/your-repo.git"
            git push origin main
          fi
        done
