name: Update TSC JSON on CODEOWNERS update

on:
  push:
    branches-ignore:
      - main
    paths:
      - '**/CODEOWNERS'

jobs:
  update-tsc-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update TSC JSON file
        run: |
          export CODEOWNERS_PATH=$(git diff-tree --no-commit-id --name-only -r HEAD | grep '/CODEOWNERS')
          node .github/workflows/update-tsc-json.js
       
      - name: Commit and push changes
        run: |
          #!/bin/bash
          git config user.name "GitHub Action"
          git config user.email 
          if [[ -n $(git diff --exit-code tsc.json) ]]; then
            git add tsc.json
            git commit -m "Update tsc.json with new CODEOWNERS information"
            commitId=$(git rev-parse HEAD)
           commitId=$(git rev-parse HEAD)
           authorEmail=$(git show -s --format='%ae' ${commitId})
           echo "Author email: ${authorEmail}"
            # Get the author email of the latest commit
            # Check whether the author is a bot or a human on GitHub
            response=$(curl -s "https://api.github.com/search/users?q=${authorEmail}")
            user_type=$(echo $response | jq -r '.items[0].type')
            if [[ "$user_type" == "Bot" ]]; then
            echo "The author with email ${authorEmail} is a bot."
            else
            echo "The author with email ${authorEmail} is a human."
           fi
            git push
          else
            echo "No changes to tsc.json. Skipping commit and push."
          fi
