name: Update example.txt

on:
  push:
    branches:
      - ptest

jobs:
  update_example_txt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout ptest branch
      uses: actions/checkout@v2
      with:
        ref: ptest

    - name: Checkout main branch
      run: |
        git fetch origin main:main
        git checkout main

    - name: Write hello message to example.txt
      run: |
        echo "Hello" >> example.txt

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<ishunitk989@gmail.com>"
        git add example.txt
        git commit -m "Update example.txt with a hello message"
        git push origin main
