name: Update TSC JSON on CODEOWNERS update

on:
  push:
    branches-ignore:
      - main
    paths:
      - '**/CODEOWNERS'

jobs:
  update-tsc-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update TSC JSON file
        run: |
          export CODEOWNERS_PATH=$(git diff-tree --no-commit-id --name-only -r HEAD | grep '/CODEOWNERS')
          node .github/workflows/update-tsc-json.js
       
      - name: Commit and push changes
        run: |
          #!/bin/bash
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          if [[ -n $(git diff --exit-code tsc.json) ]]; then
            git add tsc.json
            git commit -m "Update tsc.json with new CODEOWNERS information"
            commitId=$(git rev-parse HEAD)
           commitId=$(git rev-parse HEAD)
           authorEmail=$(git show -s --format='%ae' ${commitId})
           echo "Author email: ${authorEmail}"
            const { Octokit } = require("@octokit/core");
            const octokit = new Octokit({
              auth: "YOUR_PERSONAL_ACCESS_TOKEN",
            });
            const { data } = await octokit.request("GET /search/users", {
              q: authorEmail,
            });
            if (data.items.length > 0) {
              const user = data.items[0];
              if (user.type === "Bot") {
                console.log(`The author with email ${authorEmail} is a bot.`);
              } else {
                console.log(`The author with email ${authorEmail} is a human.`);
              }
            } else {
              console.log(`No user found with email ${authorEmail}.`);
            }
           git push
          else
            echo "No changes to tsc.json. Skipping commit and push."
          fi
