name: Update TSC JSON on CODEOWNERS update

on:
  push:
    branches-ignore:
      - main

jobs:
  update-tsc-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Update TSC JSON file
        run: node .github/workflows/update-tsc-json.js

      - name: Commit and push changes
        if: success()
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add tsc.json
          git commit -m "Update tsc.json with new CODEOWNERS information"
          git push origin ${{ github.ref }}
