name: Update TSC JSON on CODEOWNERS update

on:
  push:
    branches-ignore:
      - main
    paths:
      - '**/CODEOWNERS'

jobs:
  update-tsc-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update TSC JSON file
        run: |
          export CODEOWNERS_PATH=$(git diff-tree --no-commit-id --name-only -r HEAD | grep '/CODEOWNERS')
          node .github/workflows/update-tsc-json.js

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          if [[ -n $(git diff --exit-code tsc.json) ]]; then
            git add tsc.json
            git commit -m "Update tsc.json with new CODEOWNERS information"
            const commitId = execSync("git rev-parse HEAD", { encoding: "utf8" }).trim();
            echo "Commit ID: ${commitId}"
            git push
          else
            echo "No changes to tsc.json. Skipping commit and push."
          fi
