name: Update TSC JSON on CODEOWNERS update

on:
  push:
    branches-ignore:
      - main
    paths:
      - '**/CODEOWNERS'

jobs:
  update-tsc-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Find TSC JSON file
        id: find-tsc-json
        run: echo "::set-output name=path::$(git rev-parse --show-toplevel)/tsc.json"

      - name: Update TSC JSON file
        run: node .github/workflows/update-tsc-json.js "${{ github.event_path }}"

      - name: Commit and push changes
        if: success()
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add tsc.json
          git commit -m "Update tsc.json with new CODEOWNERS information"
          git push origin main
